apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: phani
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
