---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 3Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

...
