apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: phani
spec:
  type: LoadBalancer
  selector:
    app: result-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
