apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: phani
spec:
  type: LoadBalancer
  selector:
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
